name: expense_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
